server:
  port: 8085

spring:
  application:
    name: application-oss
  profiles:
    active: local
    include:
      - order-postgres
      - store-mongo

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.fastcampus: debug
