server:
  port: 8085

spring:
  application:
    name: application-oss
  config:
    import:
      - application-pg-toss-payments.yml
      - application-pg-pay200.yml
  profiles:
    active: local
    include:
      - order-postgres
      - member-postgres
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.fastcampus: debug
    feign.Logger: debug
