server:
  port: 8081

spring:
  profiles:
    active: local
    include:
      - member-postgres
      - order-postgres
      - payment-postgres
      - store-mongo
      - store-redis
  jpa:
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.fastcampus: debug
