server:
  port: 8082

spring:
  profiles:
    active: local
    include:
      - member-postgres
      - order-postgres
      - payment-postgres
      - store-mongo
      - store-redis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.fastcampus: debug
    org.springframework.data.mongodb.core: DEBUG
    org.mongodb.driver: DEBUG
