version: "3.8"

services:
  store-mongo:
    container_name: store-mongo
    image: brinst07/mongo-o2o:latest
    ports:
      - '27017:27017'
    networks:
      - o2o-network
  store-redis:
    container_name: store-redis
    image: devpsh/redis-o2o:latest
    ports:
      - '6379:6379'
    networks:
      - o2o-network
  order-postgres:
    container_name: order-postgres
    image: postgres:17.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: o2o
    networks:
      - o2o-network
  migrate-postgres:
    image: flyway/flyway:7
    container_name: migrate-postgres
    environment:
      - FLYWAY_DB_URL=jdbc:postgresql://order-postgres/o2o
      - FLYWAY_DB_USER=root
      - FLYWAY_DB_PASSWORD=root
    command: migrate
    volumes:
      - ./flyway/flyway.conf:/flyway/conf/flyway.conf
      - ./flyway/migration:/flyway/sql
    networks:
      - o2o-network
#  app-client:
#    container_name: app-client
#    image: yong7317/application-client:latest
#    ports:
#      - '8083:8081'
#    volumes:
#      - /home/ec2-user/backend/log:/var/log
#    networks:
#      - o2o-network
#    depends_on:
#      - store-mongo
#      - store-redis
#      - order-postgres
#  app-admin:
#    container_name: app-admin
#    image: yong7317/application-admin:latest
#    ports:
#      - '8084:8082'
#    volumes:
#      - /home/ec2-user/backend/log:/var/log
#    networks:
#      - o2o-network
#    depends_on:
#      - store-mongo
#      - store-redis
#      - order-postgres

networks:
  o2o-network:
    driver: bridge
