version: "3.8"

services:
  store-mongo:
    container_name: store-mongo
    image: brinst07/mongo-o2o:latest
    ports:
      - '27017:27017'
    networks:
      - o2o-network
  store-redis:
    container_name: store-redis
    image: redis:7.0.15
    ports:
      - '6379:6379'
    networks:
      - o2o-network
  order-postgres:
    container_name: order-postgres
    image: yong7317/postgres-o2o:latest
    platform: linux/amd64
    ports:
      - '5433:5432'
    networks:
      - o2o-network

networks:
  o2o-network:
    driver: bridge
