POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
    "storeId": "26466355",
    "roadAddress": "서울 동대문구 왕산로 123",
    "jibunAddress": "서울 동대문구 전농동 123-45",
    "detailAddress": "O2O아파트 123호",
    "orderType": "DELIVERY",
    "paymentType": "TOSS_PAY",
    "orderMenus": [
        {
            "id": "9e15c3da-cae8-4c25-8b4e-ae21a926f072",
            "quantity": 2,
            "orderMenuOptionGroups": [
                {
                    "id": "62f5ab82-6f9f-4344-964c-9a09a568df62",
                    "orderMenuOptionIds": [
                        "c5d18e3d-e643-49d6-b089-3dbb5a148800"
                    ]
                }
            ]
        },
        {
            "id": "9e15c3da-cae8-4c25-8b4e-ae21a926f072",
            "quantity": 1,
            "orderMenuOptionGroups": [
                {
                    "id": "62f5ab82-6f9f-4344-964c-9a09a568df62",
                    "orderMenuOptionIds": [
                        "fa72f6e8-1cd4-4ee7-a4ca-61167daaa3fe"
                    ]
                }
            ]
        },
        {
            "id": "51c20adf-9962-48b7-aaec-65a867d3c0c6",
            "quantity": 1,
            "orderMenuOptionGroups": [
                {
                    "id": "62bd01d0-01a3-4865-852e-a422fbf505a1",
                    "orderMenuOptionIds": [
                        "81b31574-9cd9-49ae-ad1b-3c6603f35f51"
                    ]
                }
            ]
        }
    ]
}

###
POST http://localhost:8080/api/v1/payments/approve
Content-Type: application/json

{
    "paymentKey": "",
    "orderId": "746b9cf1-5cce-4ee8-9c62-71791b1b6b80",
    "amount": 40500
}
