### 회원가입
POST http://localhost:8081/api/v1/members/join
Content-Type: application/json

{
    "signname": "user@gmail.com",
    "password": "1234",
    "nickname": "개발의민족",
    "username": "홍길동",
    "phone": "01012345678"
}

### 로그인
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
    "signname": "user@gmail.com",
    "password": "1234"
}
> {%
    client.global.set("accessToken", response.body.data.accessToken)
%}


### 주문생성
POST http://localhost:8081/api/v1/orders
Content-Type: application/json
Authorization: {{accessToken}}

{
    "storeId": "26466355",
    "roadAddress": "서울 동대문구 왕산로 123",
    "jibunAddress": "서울 동대문구 전농동 123-45",
    "detailAddress": "O2O아파트 123호",
    "orderType": "DELIVERY",
    "paymentType": "TOSS_PAY",
    "orderMenus": [
        {
            "id": "9e15c3da-cae8-4c25-8b4e-ae21a926f072",
            "quantity": 2,
            "orderMenuOptionGroups": [
                {
                    "id": "62f5ab82-6f9f-4344-964c-9a09a568df62",
                    "orderMenuOptionIds": [
                        "c5d18e3d-e643-49d6-b089-3dbb5a148800"
                    ]
                }
            ]
        },
        {
            "id": "9e15c3da-cae8-4c25-8b4e-ae21a926f072",
            "quantity": 1,
            "orderMenuOptionGroups": [
                {
                    "id": "62f5ab82-6f9f-4344-964c-9a09a568df62",
                    "orderMenuOptionIds": [
                        "fa72f6e8-1cd4-4ee7-a4ca-61167daaa3fe"
                    ]
                }
            ]
        },
        {
            "id": "51c20adf-9962-48b7-aaec-65a867d3c0c6",
            "quantity": 1,
            "orderMenuOptionGroups": [
                {
                    "id": "62bd01d0-01a3-4865-852e-a422fbf505a1",
                    "orderMenuOptionIds": [
                        "81b31574-9cd9-49ae-ad1b-3c6603f35f51"
                    ]
                }
            ]
        }
    ]
}
> {%
    client.global.set("orderId", response.body.data.orderId)
    client.global.set("totalPrice", response.body.data.totalPrice)
%}

### 리뷰 가능한 주문 조회 (Cursor 기반 페이징)
GET http://localhost:8081/api/v1/reviews/writable?cursor=2025-02-02T14:00:00&size=10
Authorization: Bearer {{accessToken}}
Content-Type: application/json


### 리뷰 등록 (파일 + JSON 데이터 전송)
POST http://localhost:8081/api/v1/reviews
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{accessToken}}

--boundary
Content-Disposition: form-data; name="reviews"
Content-Type: application/json

{
    "orderId": "{{orderId}}",
    "storeId": "26466355",
    "content": "The food was delicious and delivery was quick.",
    "totalScore": 5,
    "tasteScore": 5,
    "amountScore": 4,
    "deliveryQuality": "GOOD"
}

--boundary--
