{
 "title": "Docker App Client Log",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Docker App Client Log Status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "rate({job=\"app-client\", host!=\"\"}[1m])"
    }
   ]
  },
  {
   "title": "Request Log Records of HOST Server Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (host) (count_over_time({ filename=\"/var/log/application-client.log\", host!=\"\"} [1m]))"
    }
   ]
  },
  {
   "title": "Use Docker App Client Location",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 13, "x": 11, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/access.log\"}"
    }
   ]
  }
 ]
}