{
 "title": "Review Service Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "리뷰 API 요청 현황",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(review_api_requests_total{operation=\"addReview\"}[5m])",
     "legendFormat": "리뷰 작성"
    },
    {
     "expr": "rate(review_api_requests_total{operation=\"findWritableReview\"}[5m])",
     "legendFormat": "작성 가능 리뷰 조회"
    }
   ]
  },
  {
   "title": "이미지 업로드 현황",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(review_image_upload_total{status=\"success\"}[5m])",
     "legendFormat": "성공"
    },
    {
     "expr": "rate(review_image_upload_total{status=\"failure\"}[5m])",
     "legendFormat": "실패"
    }
   ]
  },
  {
   "title": "이미지 크기 분포",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "review_image_size_bytes", "legendFormat": "이미지 크기" }
   ]
  },
  {
   "title": "리뷰 처리 시간",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(review_processing_duration_seconds_sum{status=\"success\"}[5m]) / \nrate(review_processing_duration_seconds_count{status=\"success\"}[5m])",
     "legendFormat": "성공 케이스 처리시간"
    },
    {
     "expr": "rate(review_processing_duration_seconds_sum{status=\"failure\"}[5m]) / \nrate(review_processing_duration_seconds_count{status=\"failure\"}[5m])",
     "legendFormat": "실패 케이스 처리시간"
    }
   ]
  },
  {
   "title": "리뷰 관련 오류",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(review_failures_total[5m])) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  }
 ]
}