spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: o2o
      username: root
      password: root
      authentication-database: admin

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: store-mongo
      port: 27017
      database: o2o
      username: root
      password: root
      authentication-database: admin
