server:
  port: 8081

spring:
  profiles:
    active: local
    include:
      - member-postgres
      - member-redis
      - order-postgres
      - payment-postgres
      - store-mongo
      - store-redis
      - aws
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.fastcampus: debug
