spring:
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      stack:
        auto: false
      region.static: ${S3_REGION}
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
