spring:
  cloud:
    aws:
      s3:
        bucket: default-bucket
      stack:
        auto: false
      region.static: ap-northeast-2
      credentials:
        accessKey: default-access-key
        secretKey: default-secret-key

---

spring:
  config:
    activate:
      on-profile: local
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      stack:
        auto: false
      region.static: ${S3_REGION}
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}

---

spring:
  config:
    activate:
      on-profile: dev,prod
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      stack:
        auto: false
      region.static: ${S3_REGION}
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
