name: Deploy to Docker Hub

on:
  push:
    branches:
      - develop
    paths:
      - 'application-admin/**'
      - 'application-admin/build.gradle'
  workflow_dispatch:

jobs:
  admin-build:
    uses: ./.github/workflows/develop-admin-deploy-v1.yml
    name: "Build and Deploy for Admin"
    secrets: inherit
